name: ManualBuild

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP
      - name: Download poryscript
        run: cd tools && wget https://github.com/huderlem/poryscript/releases/download/3.3.0/poryscript-linux.zip && unzip poryscript-linux.zip -d ./ && rm ./poryscript-linux.zip && mv ./poryscript-linux ./poryscript && ls && cd ..
        # Downloads poryscript and unzips it

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Agbcc
        run: make -j${nproc} all

      - name: Download pokeemerald repo
        run: pwd && cd tools && git clone https://github.com/pret/pokeemerald
        # Clones pokeemerald repo

      - name: Install agbcc to vanilla emerald
        run: pwd && cd tools && ls && cp -r agbcc pokeemerald/tools/ && cd pokeemerald && pwd

      - name: Build pokeemerald repo
        run: pwd && cd tools && cd pokeemerald && pwd && ls && make -j${nproc}
        # builds agbcc to pokeemerald repo

      - name: Build the patch
        run: chmod -R 755 ./flips-linux && ls && ./flips-linux --create tools/pokeemerald/pokeemerald.gba pokeemerald.gba ROWE_Source.bps

      - name: Upload bps file
        uses: actions/upload-artifact@v2
        with:
          name: pokeemerald_patch
          path: ROWE_Source.bps
